# Generated by Django 3.2 on 2021-05-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=10)),
                ('OptionA', models.CharField(max_length=10)),
                ('OptionB', models.CharField(max_length=10)),
                ('OptionC', models.CharField(max_length=10)),
                ('OptionD', models.CharField(max_length=10)),
                ('correctAnswer', models.CharField(max_length=10)),
            ],
        ),
    ]
